@startuml


class App {
    
    -segments:String[]
    -classe:String
    -metodo:String
    
    
    +App(req:HttpServletRequest)
    -setClasse()
    -formataNomeClasse()
    -setMetodo()
    +getMetodo():String
    +getClasse():String 

}

@enduml