@startuml

class Filtro<? implements Filter>{
   +destroy()
   +init( filterConfig:FilterConfig)
   +doFilter(request:ServletRequest , response:ServletResponse , chain:FilterChain ) 
   - entityManager:EntityManager
   
   
   +usuarioLogado(req:HttpServletRequest ):boolean
   +isAdmin(req:HttpServletRequest ):boolean
}
@enduml