@startuml


class TreinamentoDAO <? implements DAO<Treinamento>> {
    
    entityManage:EntityManager 
    + Cadastrar(treina:Treinamento)
    + Alterar( obj:Treinamento)
    + ConsultarTudo(string:String):ArrayList<Treinamento>
    + Treinamento Consultar(codigo:Integer):Treinamento
    + Deletar(codigo:Integer)       
}

@enduml