@startuml

class UsuarioDAO <? implements DAO<Usuario>>{
    
       entityManager:EntityManager 
    
    + buscaUsuario(login:String):Usuario
    + Cadastrar(obj:Usuario)
    + ConsultarTudo(string:String)ArrayList<Usuario>
    + Consultar(codigo:Integer):Usuario
    + Alterar(obj:Usuario) 
    + Deletar(codigo:Integer)

}


@enduml