@startuml

 class AdministradorModel<? implements Tarefa> {
    
    -{static}permAdmin:String[]
    +getPermAdmin(req:HttpServletRequest , resp:HttpServletResponse ):String[]
    +usuarios(req:HttpServletRequest , resp:HttpServletResponse):String
    +cadastrar(req:HttpServletRequest , resp:HttpServletResponse):String
    +alterar(req:HttpServletRequest , resp:HttpServletResponse):String
    +listartudo(req:HttpServletRequest , resp:HttpServletResponse):String
    +buscar(req:HttpServletRequest , resp:HttpServletResponse):String
    +excluir(req:HttpServletRequest , resp:HttpServletResponse):String
}

@enduml