@startuml
class FaltaModel <? implements Tarefa>{
    - {static}permAdmin:String[] 
    - faltaDAO:FaltaDAO 
    - faltas:ArrayList<Falta> 
 
    + getPermAdmin( req:HttpServletRequest, resp:HttpServletResponse):String[]
    + cadastrar( req:HttpServletRequest, resp:HttpServletResponse):String
    + alterar( req:HttpServletRequest, resp:HttpServletResponse):String
    + listartudo( req:HttpServletRequest, resp:HttpServletResponse):String
    + buscar( req:HttpServletRequest, resp:HttpServletResponse):String
    + excluir( req:HttpServletRequest, resp:HttpServletResponse):String
    
}

@enduml
