/' Para exibir os diagramas é necessário obter o graphviz e o plugin plantuml para o netbeans
http://plugins.netbeans.org/plugin/49069/plantuml
http://www.graphviz.org/Download_windows.php
 '/
@startuml
class Treinamento {
    -codigo:Integer
    -descricao: String 
    -dataincio:Date 
    -datafim:Date 
    -hora:Date
    -turma:String
    -laboratorio:String
    -usuario:Usuario 
    +getDescricao():String
    +setDescricao(descricao:String):void
    +getDatainicio():Date
    +setDatainicio(dataincio:Date):void
    +getDatafim():Date
    +setDatafim(datafim:Date):void
    +getHora():Date
    +setHora(hora:Date):void
    +getTurma():String
    +setTurma(String turma):void
    +getLaboratorio():String
    +setLaboratorio(String laboratorio):void
    +getUsuario():Usuario
    +setUsuario(Usuario usuario):void
    +getCodigo():Integer
    +setCodigo(int codigo):void
}

@enduml
